# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-15 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Big',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'big',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.FloatField()),
                ('imgdir', models.CharField(max_length=200)),
                ('category_id', models.IntegerField()),
                ('big_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clothes.Big')),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.Brand')),
            ],
            options={
                'db_table': 'good',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=255)),
                ('headimg', models.CharField(default='img/imgs/desk.jpg', max_length=100)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
