# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-11 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cart',
            new_name='Card',
        ),
        migrations.AlterModelTable(
            name='card',
            table='card',
        ),
    ]
