# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-10 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0003_auto_20190110_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='user',
        ),
    ]
