# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-14 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0004_auto_20190111_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='headimg',
            field=models.ImageField(default='img/imgs/desk.jpg', upload_to=''),
        ),
    ]
