# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-16 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0005_auto_20190116_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='category_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='good',
            name='old_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
