# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-14 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0005_user_headimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='headimg',
            field=models.CharField(default='img/imgs/desk.jpg', max_length=100),
        ),
    ]
