# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-16 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0007_auto_20190116_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='goodname',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='goodprice',
        ),
        migrations.AlterField(
            model_name='cart',
            name='good_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.Good'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.User'),
        ),
    ]
