# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-16 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0009_auto_20190116_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodnum', models.IntegerField()),
                ('goodcolor', models.CharField(max_length=20)),
                ('goodsize', models.CharField(max_length=20)),
                ('good_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.Good')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.User')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
