# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-16 11:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0010_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='good_id',
            new_name='good',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='user',
        ),
    ]
