# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-18 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0011_auto_20190116_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='isselect',
            field=models.BooleanField(default=True),
        ),
    ]
