# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-18 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0012_cart_isselect'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('identifier', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.User')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderGood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('size', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.Good')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.Order')),
            ],
            options={
                'db_table': 'ordergood',
            },
        ),
    ]
