# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-18 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0013_order_ordergood'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordergood',
            old_name='goods',
            new_name='good',
        ),
    ]
